name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files to EC2
      run: |
        scp -o StrictHostKeyChecking=no -i /home/runner/.ssh/projects.pem -r SampleWebApp ec2-user@${{ secrets.EC2_PUBLIC_IP }}:/home/ec2-user/

    - name: Install and run application on EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i /home/runner/.ssh/projects.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          sudo yum update -y
          sudo yum install -y httpd
          sudo systemctl start httpd
          sudo systemctl enable httpd
          sudo cp -r /home/ec2-user/SampleWebApp/* /var/www/html/
          sudo systemctl restart httpd
        EOF
